services:
  db:
    image: postgres:16
    container_name: comp-app-database
    environment:
      POSTGRES_DB: ${DB_NAME:-comp}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-pass}
    ports:
      - "${DB_PORT:-5555}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD_SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-comp}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  migrator:
    image: migrate/migrate:4
    container_name: migrator
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
    entrypoint: >
      sh -c migrate -path /migrations -database '${POSTGRES_DSN}' up
    volumes:
      - ./migrations:/migrations:ro
    restart: "no"


volumes:
  pgdata:
