// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: search.proto

package search

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Search_Ping_FullMethodName                       = "/search.Search/Ping"
	Search_GetGPU_FullMethodName                     = "/search.Search/GetGPU"
	Search_GetCPU_FullMethodName                     = "/search.Search/GetCPU"
	Search_GetMotherboard_FullMethodName             = "/search.Search/GetMotherboard"
	Search_GetRAMKit_FullMethodName                  = "/search.Search/GetRAMKit"
	Search_GetPSU_FullMethodName                     = "/search.Search/GetPSU"
	Search_GetCase_FullMethodName                    = "/search.Search/GetCase"
	Search_GetCpuCooler_FullMethodName               = "/search.Search/GetCpuCooler"
	Search_GetStorageDrive_FullMethodName            = "/search.Search/GetStorageDrive"
	Search_GetCpuSocket_FullMethodName               = "/search.Search/GetCpuSocket"
	Search_GetMotherboardFormFactor_FullMethodName   = "/search.Search/GetMotherboardFormFactor"
	Search_GetUser_FullMethodName                    = "/search.Search/GetUser"
	Search_GetShop_FullMethodName                    = "/search.Search/GetShop"
	Search_GetProductOffer_FullMethodName            = "/search.Search/GetProductOffer"
	Search_GetAssembly_FullMethodName                = "/search.Search/GetAssembly"
	Search_ListGPUs_FullMethodName                   = "/search.Search/ListGPUs"
	Search_ListCPUs_FullMethodName                   = "/search.Search/ListCPUs"
	Search_ListMotherboards_FullMethodName           = "/search.Search/ListMotherboards"
	Search_ListRAMKits_FullMethodName                = "/search.Search/ListRAMKits"
	Search_ListPSUs_FullMethodName                   = "/search.Search/ListPSUs"
	Search_ListCases_FullMethodName                  = "/search.Search/ListCases"
	Search_ListCpuCoolers_FullMethodName             = "/search.Search/ListCpuCoolers"
	Search_ListStorageDrives_FullMethodName          = "/search.Search/ListStorageDrives"
	Search_ListCpuSockets_FullMethodName             = "/search.Search/ListCpuSockets"
	Search_ListMotherboardFormFactors_FullMethodName = "/search.Search/ListMotherboardFormFactors"
	Search_ListUsers_FullMethodName                  = "/search.Search/ListUsers"
	Search_ListShops_FullMethodName                  = "/search.Search/ListShops"
	Search_ListProductOffers_FullMethodName          = "/search.Search/ListProductOffers"
	Search_ListAssemblies_FullMethodName             = "/search.Search/ListAssemblies"
	Search_ListAssembliesByUser_FullMethodName       = "/search.Search/ListAssembliesByUser"
	Search_SearchComponents_FullMethodName           = "/search.Search/SearchComponents"
	Search_SearchAssemblies_FullMethodName           = "/search.Search/SearchAssemblies"
	Search_CheckCompatibility_FullMethodName         = "/search.Search/CheckCompatibility"
	Search_GetCompatibleComponents_FullMethodName    = "/search.Search/GetCompatibleComponents"
	Search_RecommendComponents_FullMethodName        = "/search.Search/RecommendComponents"
	Search_GetComponentPrices_FullMethodName         = "/search.Search/GetComponentPrices"
	Search_GetBestOffers_FullMethodName              = "/search.Search/GetBestOffers"
)

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get single item by ID
	GetGPU(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GPU, error)
	GetCPU(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CPU, error)
	GetMotherboard(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Motherboard, error)
	GetRAMKit(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*RAMKit, error)
	GetPSU(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*PSU, error)
	GetCase(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Case, error)
	GetCpuCooler(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CpuCooler, error)
	GetStorageDrive(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*StorageDrive, error)
	GetCpuSocket(ctx context.Context, in *GetByCodeRequest, opts ...grpc.CallOption) (*CpuSocket, error)
	GetMotherboardFormFactor(ctx context.Context, in *GetByCodeRequest, opts ...grpc.CallOption) (*MotherboardFormFactor, error)
	GetUser(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*User, error)
	GetShop(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Shop, error)
	GetProductOffer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ProductOffer, error)
	GetAssembly(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Assembly, error)
	// List items with pagination and filtering
	ListGPUs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*GPUList, error)
	ListCPUs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CPUList, error)
	ListMotherboards(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*MotherboardList, error)
	ListRAMKits(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*RAMKitList, error)
	ListPSUs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PSUList, error)
	ListCases(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CaseList, error)
	ListCpuCoolers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CpuCoolerList, error)
	ListStorageDrives(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*StorageDriveList, error)
	ListCpuSockets(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CpuSocketList, error)
	ListMotherboardFormFactors(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*MotherboardFormFactorList, error)
	ListUsers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*UserList, error)
	ListShops(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ShopList, error)
	ListProductOffers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ProductOfferList, error)
	ListAssemblies(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*AssemblyList, error)
	ListAssembliesByUser(ctx context.Context, in *ListByUserRequest, opts ...grpc.CallOption) (*AssemblyList, error)
	// Advanced search methods
	SearchComponents(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchAssemblies(ctx context.Context, in *SearchAssembliesRequest, opts ...grpc.CallOption) (*AssemblyList, error)
	// Compatibility check
	CheckCompatibility(ctx context.Context, in *CheckCompatibilityRequest, opts ...grpc.CallOption) (*ValidationResult, error)
	// Component recommendations
	GetCompatibleComponents(ctx context.Context, in *CompatibilityRequest, opts ...grpc.CallOption) (*CompatibleComponents, error)
	RecommendComponents(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
	// Price and availability
	GetComponentPrices(ctx context.Context, in *ComponentPricesRequest, opts ...grpc.CallOption) (*PriceList, error)
	GetBestOffers(ctx context.Context, in *OffersRequest, opts ...grpc.CallOption) (*OfferList, error)
}

type searchClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchClient(cc grpc.ClientConnInterface) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Search_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetGPU(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GPU, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GPU)
	err := c.cc.Invoke(ctx, Search_GetGPU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetCPU(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CPU, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CPU)
	err := c.cc.Invoke(ctx, Search_GetCPU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetMotherboard(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Motherboard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Motherboard)
	err := c.cc.Invoke(ctx, Search_GetMotherboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetRAMKit(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*RAMKit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAMKit)
	err := c.cc.Invoke(ctx, Search_GetRAMKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetPSU(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*PSU, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PSU)
	err := c.cc.Invoke(ctx, Search_GetPSU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetCase(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Case, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Case)
	err := c.cc.Invoke(ctx, Search_GetCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetCpuCooler(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CpuCooler, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpuCooler)
	err := c.cc.Invoke(ctx, Search_GetCpuCooler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetStorageDrive(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*StorageDrive, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageDrive)
	err := c.cc.Invoke(ctx, Search_GetStorageDrive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetCpuSocket(ctx context.Context, in *GetByCodeRequest, opts ...grpc.CallOption) (*CpuSocket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpuSocket)
	err := c.cc.Invoke(ctx, Search_GetCpuSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetMotherboardFormFactor(ctx context.Context, in *GetByCodeRequest, opts ...grpc.CallOption) (*MotherboardFormFactor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MotherboardFormFactor)
	err := c.cc.Invoke(ctx, Search_GetMotherboardFormFactor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetUser(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, Search_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetShop(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Shop, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Shop)
	err := c.cc.Invoke(ctx, Search_GetShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetProductOffer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ProductOffer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductOffer)
	err := c.cc.Invoke(ctx, Search_GetProductOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetAssembly(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Assembly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assembly)
	err := c.cc.Invoke(ctx, Search_GetAssembly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListGPUs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*GPUList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GPUList)
	err := c.cc.Invoke(ctx, Search_ListGPUs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListCPUs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CPUList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CPUList)
	err := c.cc.Invoke(ctx, Search_ListCPUs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListMotherboards(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*MotherboardList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MotherboardList)
	err := c.cc.Invoke(ctx, Search_ListMotherboards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListRAMKits(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*RAMKitList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAMKitList)
	err := c.cc.Invoke(ctx, Search_ListRAMKits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListPSUs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PSUList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PSUList)
	err := c.cc.Invoke(ctx, Search_ListPSUs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListCases(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CaseList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaseList)
	err := c.cc.Invoke(ctx, Search_ListCases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListCpuCoolers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CpuCoolerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpuCoolerList)
	err := c.cc.Invoke(ctx, Search_ListCpuCoolers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListStorageDrives(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*StorageDriveList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageDriveList)
	err := c.cc.Invoke(ctx, Search_ListStorageDrives_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListCpuSockets(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CpuSocketList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpuSocketList)
	err := c.cc.Invoke(ctx, Search_ListCpuSockets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListMotherboardFormFactors(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*MotherboardFormFactorList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MotherboardFormFactorList)
	err := c.cc.Invoke(ctx, Search_ListMotherboardFormFactors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListUsers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*UserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserList)
	err := c.cc.Invoke(ctx, Search_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListShops(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ShopList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopList)
	err := c.cc.Invoke(ctx, Search_ListShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListProductOffers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ProductOfferList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductOfferList)
	err := c.cc.Invoke(ctx, Search_ListProductOffers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListAssemblies(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*AssemblyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssemblyList)
	err := c.cc.Invoke(ctx, Search_ListAssemblies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ListAssembliesByUser(ctx context.Context, in *ListByUserRequest, opts ...grpc.CallOption) (*AssemblyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssemblyList)
	err := c.cc.Invoke(ctx, Search_ListAssembliesByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SearchComponents(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Search_SearchComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SearchAssemblies(ctx context.Context, in *SearchAssembliesRequest, opts ...grpc.CallOption) (*AssemblyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssemblyList)
	err := c.cc.Invoke(ctx, Search_SearchAssemblies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) CheckCompatibility(ctx context.Context, in *CheckCompatibilityRequest, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, Search_CheckCompatibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetCompatibleComponents(ctx context.Context, in *CompatibilityRequest, opts ...grpc.CallOption) (*CompatibleComponents, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompatibleComponents)
	err := c.cc.Invoke(ctx, Search_GetCompatibleComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) RecommendComponents(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, Search_RecommendComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetComponentPrices(ctx context.Context, in *ComponentPricesRequest, opts ...grpc.CallOption) (*PriceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceList)
	err := c.cc.Invoke(ctx, Search_GetComponentPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetBestOffers(ctx context.Context, in *OffersRequest, opts ...grpc.CallOption) (*OfferList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferList)
	err := c.cc.Invoke(ctx, Search_GetBestOffers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
// All implementations must embed UnimplementedSearchServer
// for forward compatibility.
type SearchServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Get single item by ID
	GetGPU(context.Context, *GetRequest) (*GPU, error)
	GetCPU(context.Context, *GetRequest) (*CPU, error)
	GetMotherboard(context.Context, *GetRequest) (*Motherboard, error)
	GetRAMKit(context.Context, *GetRequest) (*RAMKit, error)
	GetPSU(context.Context, *GetRequest) (*PSU, error)
	GetCase(context.Context, *GetRequest) (*Case, error)
	GetCpuCooler(context.Context, *GetRequest) (*CpuCooler, error)
	GetStorageDrive(context.Context, *GetRequest) (*StorageDrive, error)
	GetCpuSocket(context.Context, *GetByCodeRequest) (*CpuSocket, error)
	GetMotherboardFormFactor(context.Context, *GetByCodeRequest) (*MotherboardFormFactor, error)
	GetUser(context.Context, *GetRequest) (*User, error)
	GetShop(context.Context, *GetRequest) (*Shop, error)
	GetProductOffer(context.Context, *GetRequest) (*ProductOffer, error)
	GetAssembly(context.Context, *GetRequest) (*Assembly, error)
	// List items with pagination and filtering
	ListGPUs(context.Context, *ListRequest) (*GPUList, error)
	ListCPUs(context.Context, *ListRequest) (*CPUList, error)
	ListMotherboards(context.Context, *ListRequest) (*MotherboardList, error)
	ListRAMKits(context.Context, *ListRequest) (*RAMKitList, error)
	ListPSUs(context.Context, *ListRequest) (*PSUList, error)
	ListCases(context.Context, *ListRequest) (*CaseList, error)
	ListCpuCoolers(context.Context, *ListRequest) (*CpuCoolerList, error)
	ListStorageDrives(context.Context, *ListRequest) (*StorageDriveList, error)
	ListCpuSockets(context.Context, *ListRequest) (*CpuSocketList, error)
	ListMotherboardFormFactors(context.Context, *ListRequest) (*MotherboardFormFactorList, error)
	ListUsers(context.Context, *ListRequest) (*UserList, error)
	ListShops(context.Context, *ListRequest) (*ShopList, error)
	ListProductOffers(context.Context, *ListRequest) (*ProductOfferList, error)
	ListAssemblies(context.Context, *ListRequest) (*AssemblyList, error)
	ListAssembliesByUser(context.Context, *ListByUserRequest) (*AssemblyList, error)
	// Advanced search methods
	SearchComponents(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchAssemblies(context.Context, *SearchAssembliesRequest) (*AssemblyList, error)
	// Compatibility check
	CheckCompatibility(context.Context, *CheckCompatibilityRequest) (*ValidationResult, error)
	// Component recommendations
	GetCompatibleComponents(context.Context, *CompatibilityRequest) (*CompatibleComponents, error)
	RecommendComponents(context.Context, *RecommendationRequest) (*RecommendationResponse, error)
	// Price and availability
	GetComponentPrices(context.Context, *ComponentPricesRequest) (*PriceList, error)
	GetBestOffers(context.Context, *OffersRequest) (*OfferList, error)
	mustEmbedUnimplementedSearchServer()
}

// UnimplementedSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServer struct{}

func (UnimplementedSearchServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSearchServer) GetGPU(context.Context, *GetRequest) (*GPU, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGPU not implemented")
}
func (UnimplementedSearchServer) GetCPU(context.Context, *GetRequest) (*CPU, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCPU not implemented")
}
func (UnimplementedSearchServer) GetMotherboard(context.Context, *GetRequest) (*Motherboard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMotherboard not implemented")
}
func (UnimplementedSearchServer) GetRAMKit(context.Context, *GetRequest) (*RAMKit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRAMKit not implemented")
}
func (UnimplementedSearchServer) GetPSU(context.Context, *GetRequest) (*PSU, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPSU not implemented")
}
func (UnimplementedSearchServer) GetCase(context.Context, *GetRequest) (*Case, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCase not implemented")
}
func (UnimplementedSearchServer) GetCpuCooler(context.Context, *GetRequest) (*CpuCooler, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCpuCooler not implemented")
}
func (UnimplementedSearchServer) GetStorageDrive(context.Context, *GetRequest) (*StorageDrive, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorageDrive not implemented")
}
func (UnimplementedSearchServer) GetCpuSocket(context.Context, *GetByCodeRequest) (*CpuSocket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCpuSocket not implemented")
}
func (UnimplementedSearchServer) GetMotherboardFormFactor(context.Context, *GetByCodeRequest) (*MotherboardFormFactor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMotherboardFormFactor not implemented")
}
func (UnimplementedSearchServer) GetUser(context.Context, *GetRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedSearchServer) GetShop(context.Context, *GetRequest) (*Shop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShop not implemented")
}
func (UnimplementedSearchServer) GetProductOffer(context.Context, *GetRequest) (*ProductOffer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductOffer not implemented")
}
func (UnimplementedSearchServer) GetAssembly(context.Context, *GetRequest) (*Assembly, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssembly not implemented")
}
func (UnimplementedSearchServer) ListGPUs(context.Context, *ListRequest) (*GPUList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGPUs not implemented")
}
func (UnimplementedSearchServer) ListCPUs(context.Context, *ListRequest) (*CPUList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCPUs not implemented")
}
func (UnimplementedSearchServer) ListMotherboards(context.Context, *ListRequest) (*MotherboardList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMotherboards not implemented")
}
func (UnimplementedSearchServer) ListRAMKits(context.Context, *ListRequest) (*RAMKitList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRAMKits not implemented")
}
func (UnimplementedSearchServer) ListPSUs(context.Context, *ListRequest) (*PSUList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPSUs not implemented")
}
func (UnimplementedSearchServer) ListCases(context.Context, *ListRequest) (*CaseList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCases not implemented")
}
func (UnimplementedSearchServer) ListCpuCoolers(context.Context, *ListRequest) (*CpuCoolerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCpuCoolers not implemented")
}
func (UnimplementedSearchServer) ListStorageDrives(context.Context, *ListRequest) (*StorageDriveList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStorageDrives not implemented")
}
func (UnimplementedSearchServer) ListCpuSockets(context.Context, *ListRequest) (*CpuSocketList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCpuSockets not implemented")
}
func (UnimplementedSearchServer) ListMotherboardFormFactors(context.Context, *ListRequest) (*MotherboardFormFactorList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMotherboardFormFactors not implemented")
}
func (UnimplementedSearchServer) ListUsers(context.Context, *ListRequest) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedSearchServer) ListShops(context.Context, *ListRequest) (*ShopList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShops not implemented")
}
func (UnimplementedSearchServer) ListProductOffers(context.Context, *ListRequest) (*ProductOfferList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductOffers not implemented")
}
func (UnimplementedSearchServer) ListAssemblies(context.Context, *ListRequest) (*AssemblyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssemblies not implemented")
}
func (UnimplementedSearchServer) ListAssembliesByUser(context.Context, *ListByUserRequest) (*AssemblyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssembliesByUser not implemented")
}
func (UnimplementedSearchServer) SearchComponents(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchComponents not implemented")
}
func (UnimplementedSearchServer) SearchAssemblies(context.Context, *SearchAssembliesRequest) (*AssemblyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAssemblies not implemented")
}
func (UnimplementedSearchServer) CheckCompatibility(context.Context, *CheckCompatibilityRequest) (*ValidationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCompatibility not implemented")
}
func (UnimplementedSearchServer) GetCompatibleComponents(context.Context, *CompatibilityRequest) (*CompatibleComponents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompatibleComponents not implemented")
}
func (UnimplementedSearchServer) RecommendComponents(context.Context, *RecommendationRequest) (*RecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendComponents not implemented")
}
func (UnimplementedSearchServer) GetComponentPrices(context.Context, *ComponentPricesRequest) (*PriceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentPrices not implemented")
}
func (UnimplementedSearchServer) GetBestOffers(context.Context, *OffersRequest) (*OfferList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBestOffers not implemented")
}
func (UnimplementedSearchServer) mustEmbedUnimplementedSearchServer() {}
func (UnimplementedSearchServer) testEmbeddedByValue()                {}

// UnsafeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServer will
// result in compilation errors.
type UnsafeSearchServer interface {
	mustEmbedUnimplementedSearchServer()
}

func RegisterSearchServer(s grpc.ServiceRegistrar, srv SearchServer) {
	// If the following call pancis, it indicates UnimplementedSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Search_ServiceDesc, srv)
}

func _Search_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetGPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetGPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetGPU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetGPU(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetCPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetCPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetCPU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetCPU(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetMotherboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetMotherboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetMotherboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetMotherboard(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetRAMKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetRAMKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetRAMKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetRAMKit(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetPSU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetPSU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetPSU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetPSU(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetCase(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetCpuCooler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetCpuCooler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetCpuCooler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetCpuCooler(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetStorageDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetStorageDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetStorageDrive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetStorageDrive(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetCpuSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetCpuSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetCpuSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetCpuSocket(ctx, req.(*GetByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetMotherboardFormFactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetMotherboardFormFactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetMotherboardFormFactor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetMotherboardFormFactor(ctx, req.(*GetByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetUser(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetShop(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetProductOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetProductOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetProductOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetProductOffer(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetAssembly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetAssembly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetAssembly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetAssembly(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListGPUs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListGPUs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListGPUs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListGPUs(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListCPUs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListCPUs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListCPUs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListCPUs(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListMotherboards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListMotherboards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListMotherboards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListMotherboards(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListRAMKits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListRAMKits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListRAMKits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListRAMKits(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListPSUs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListPSUs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListPSUs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListPSUs(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListCases(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListCpuCoolers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListCpuCoolers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListCpuCoolers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListCpuCoolers(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListStorageDrives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListStorageDrives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListStorageDrives_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListStorageDrives(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListCpuSockets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListCpuSockets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListCpuSockets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListCpuSockets(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListMotherboardFormFactors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListMotherboardFormFactors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListMotherboardFormFactors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListMotherboardFormFactors(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListUsers(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListShops(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListProductOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListProductOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListProductOffers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListProductOffers(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListAssemblies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListAssemblies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListAssemblies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListAssemblies(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ListAssembliesByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ListAssembliesByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_ListAssembliesByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ListAssembliesByUser(ctx, req.(*ListByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SearchComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchComponents(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SearchAssemblies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAssembliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchAssemblies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchAssemblies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchAssemblies(ctx, req.(*SearchAssembliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_CheckCompatibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCompatibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).CheckCompatibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_CheckCompatibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).CheckCompatibility(ctx, req.(*CheckCompatibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetCompatibleComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompatibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetCompatibleComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetCompatibleComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetCompatibleComponents(ctx, req.(*CompatibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_RecommendComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).RecommendComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_RecommendComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).RecommendComponents(ctx, req.(*RecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetComponentPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComponentPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetComponentPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetComponentPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetComponentPrices(ctx, req.(*ComponentPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetBestOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetBestOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetBestOffers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetBestOffers(ctx, req.(*OffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Search_ServiceDesc is the grpc.ServiceDesc for Search service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Search_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Search_Ping_Handler,
		},
		{
			MethodName: "GetGPU",
			Handler:    _Search_GetGPU_Handler,
		},
		{
			MethodName: "GetCPU",
			Handler:    _Search_GetCPU_Handler,
		},
		{
			MethodName: "GetMotherboard",
			Handler:    _Search_GetMotherboard_Handler,
		},
		{
			MethodName: "GetRAMKit",
			Handler:    _Search_GetRAMKit_Handler,
		},
		{
			MethodName: "GetPSU",
			Handler:    _Search_GetPSU_Handler,
		},
		{
			MethodName: "GetCase",
			Handler:    _Search_GetCase_Handler,
		},
		{
			MethodName: "GetCpuCooler",
			Handler:    _Search_GetCpuCooler_Handler,
		},
		{
			MethodName: "GetStorageDrive",
			Handler:    _Search_GetStorageDrive_Handler,
		},
		{
			MethodName: "GetCpuSocket",
			Handler:    _Search_GetCpuSocket_Handler,
		},
		{
			MethodName: "GetMotherboardFormFactor",
			Handler:    _Search_GetMotherboardFormFactor_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Search_GetUser_Handler,
		},
		{
			MethodName: "GetShop",
			Handler:    _Search_GetShop_Handler,
		},
		{
			MethodName: "GetProductOffer",
			Handler:    _Search_GetProductOffer_Handler,
		},
		{
			MethodName: "GetAssembly",
			Handler:    _Search_GetAssembly_Handler,
		},
		{
			MethodName: "ListGPUs",
			Handler:    _Search_ListGPUs_Handler,
		},
		{
			MethodName: "ListCPUs",
			Handler:    _Search_ListCPUs_Handler,
		},
		{
			MethodName: "ListMotherboards",
			Handler:    _Search_ListMotherboards_Handler,
		},
		{
			MethodName: "ListRAMKits",
			Handler:    _Search_ListRAMKits_Handler,
		},
		{
			MethodName: "ListPSUs",
			Handler:    _Search_ListPSUs_Handler,
		},
		{
			MethodName: "ListCases",
			Handler:    _Search_ListCases_Handler,
		},
		{
			MethodName: "ListCpuCoolers",
			Handler:    _Search_ListCpuCoolers_Handler,
		},
		{
			MethodName: "ListStorageDrives",
			Handler:    _Search_ListStorageDrives_Handler,
		},
		{
			MethodName: "ListCpuSockets",
			Handler:    _Search_ListCpuSockets_Handler,
		},
		{
			MethodName: "ListMotherboardFormFactors",
			Handler:    _Search_ListMotherboardFormFactors_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Search_ListUsers_Handler,
		},
		{
			MethodName: "ListShops",
			Handler:    _Search_ListShops_Handler,
		},
		{
			MethodName: "ListProductOffers",
			Handler:    _Search_ListProductOffers_Handler,
		},
		{
			MethodName: "ListAssemblies",
			Handler:    _Search_ListAssemblies_Handler,
		},
		{
			MethodName: "ListAssembliesByUser",
			Handler:    _Search_ListAssembliesByUser_Handler,
		},
		{
			MethodName: "SearchComponents",
			Handler:    _Search_SearchComponents_Handler,
		},
		{
			MethodName: "SearchAssemblies",
			Handler:    _Search_SearchAssemblies_Handler,
		},
		{
			MethodName: "CheckCompatibility",
			Handler:    _Search_CheckCompatibility_Handler,
		},
		{
			MethodName: "GetCompatibleComponents",
			Handler:    _Search_GetCompatibleComponents_Handler,
		},
		{
			MethodName: "RecommendComponents",
			Handler:    _Search_RecommendComponents_Handler,
		},
		{
			MethodName: "GetComponentPrices",
			Handler:    _Search_GetComponentPrices_Handler,
		},
		{
			MethodName: "GetBestOffers",
			Handler:    _Search_GetBestOffers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
