// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: update.proto

package update

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Update_Ping_FullMethodName                               = "/update.Update/Ping"
	Update_AddGpu_FullMethodName                             = "/update.Update/AddGpu"
	Update_UpdateGpu_FullMethodName                          = "/update.Update/UpdateGpu"
	Update_DeleteGpu_FullMethodName                          = "/update.Update/DeleteGpu"
	Update_AddCpuCooler_FullMethodName                       = "/update.Update/AddCpuCooler"
	Update_UpdateCpuCooler_FullMethodName                    = "/update.Update/UpdateCpuCooler"
	Update_DeleteCpuCooler_FullMethodName                    = "/update.Update/DeleteCpuCooler"
	Update_AddCase_FullMethodName                            = "/update.Update/AddCase"
	Update_UpdateCase_FullMethodName                         = "/update.Update/UpdateCase"
	Update_DeleteCase_FullMethodName                         = "/update.Update/DeleteCase"
	Update_AddPsu_FullMethodName                             = "/update.Update/AddPsu"
	Update_UpdatePsu_FullMethodName                          = "/update.Update/UpdatePsu"
	Update_DeletePsu_FullMethodName                          = "/update.Update/DeletePsu"
	Update_AddCpuSocket_FullMethodName                       = "/update.Update/AddCpuSocket"
	Update_UpdateCpuSocket_FullMethodName                    = "/update.Update/UpdateCpuSocket"
	Update_DeleteCpuSocket_FullMethodName                    = "/update.Update/DeleteCpuSocket"
	Update_AddMotherboardFormFactor_FullMethodName           = "/update.Update/AddMotherboardFormFactor"
	Update_UpdateMotherboardFormFactor_FullMethodName        = "/update.Update/UpdateMotherboardFormFactor"
	Update_DeleteMotherboardFormFactor_FullMethodName        = "/update.Update/DeleteMotherboardFormFactor"
	Update_AddCpu_FullMethodName                             = "/update.Update/AddCpu"
	Update_UpdateCpu_FullMethodName                          = "/update.Update/UpdateCpu"
	Update_DeleteCpu_FullMethodName                          = "/update.Update/DeleteCpu"
	Update_AddMotherboard_FullMethodName                     = "/update.Update/AddMotherboard"
	Update_UpdateMotherboard_FullMethodName                  = "/update.Update/UpdateMotherboard"
	Update_DeleteMotherboard_FullMethodName                  = "/update.Update/DeleteMotherboard"
	Update_AddRAMKit_FullMethodName                          = "/update.Update/AddRAMKit"
	Update_UpdateRAMKit_FullMethodName                       = "/update.Update/UpdateRAMKit"
	Update_DeleteRAMKit_FullMethodName                       = "/update.Update/DeleteRAMKit"
	Update_AddStorageDrive_FullMethodName                    = "/update.Update/AddStorageDrive"
	Update_UpdateStorageDrive_FullMethodName                 = "/update.Update/UpdateStorageDrive"
	Update_DeleteStorageDrive_FullMethodName                 = "/update.Update/DeleteStorageDrive"
	Update_AddUser_FullMethodName                            = "/update.Update/AddUser"
	Update_UpdateUser_FullMethodName                         = "/update.Update/UpdateUser"
	Update_DeleteUser_FullMethodName                         = "/update.Update/DeleteUser"
	Update_AddShop_FullMethodName                            = "/update.Update/AddShop"
	Update_UpdateShop_FullMethodName                         = "/update.Update/UpdateShop"
	Update_DeleteShop_FullMethodName                         = "/update.Update/DeleteShop"
	Update_AddProductOffer_FullMethodName                    = "/update.Update/AddProductOffer"
	Update_UpdateProductOffer_FullMethodName                 = "/update.Update/UpdateProductOffer"
	Update_DeleteProductOffer_FullMethodName                 = "/update.Update/DeleteProductOffer"
	Update_AddAssembly_FullMethodName                        = "/update.Update/AddAssembly"
	Update_UpdateAssembly_FullMethodName                     = "/update.Update/UpdateAssembly"
	Update_DeleteAssembly_FullMethodName                     = "/update.Update/DeleteAssembly"
	Update_AddCoolerSocket_FullMethodName                    = "/update.Update/AddCoolerSocket"
	Update_DeleteCoolerSocket_FullMethodName                 = "/update.Update/DeleteCoolerSocket"
	Update_DeleteCoolerSocketsByCooler_FullMethodName        = "/update.Update/DeleteCoolerSocketsByCooler"
	Update_AddCaseFormFactorSupport_FullMethodName           = "/update.Update/AddCaseFormFactorSupport"
	Update_DeleteCaseFormFactorSupport_FullMethodName        = "/update.Update/DeleteCaseFormFactorSupport"
	Update_DeleteCaseFormFactorSupportsByCase_FullMethodName = "/update.Update/DeleteCaseFormFactorSupportsByCase"
	Update_AddAssemblyRAMKit_FullMethodName                  = "/update.Update/AddAssemblyRAMKit"
	Update_DeleteAssemblyRAMKit_FullMethodName               = "/update.Update/DeleteAssemblyRAMKit"
	Update_DeleteAssemblyRAMKitsByAssembly_FullMethodName    = "/update.Update/DeleteAssemblyRAMKitsByAssembly"
	Update_AddAssemblyDrive_FullMethodName                   = "/update.Update/AddAssemblyDrive"
	Update_DeleteAssemblyDrive_FullMethodName                = "/update.Update/DeleteAssemblyDrive"
	Update_DeleteAssemblyDrivesByAssembly_FullMethodName     = "/update.Update/DeleteAssemblyDrivesByAssembly"
)

// UpdateClient is the client API for Update service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GPU methods
	AddGpu(ctx context.Context, in *GpuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateGpu(ctx context.Context, in *UpdateGpuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteGpu(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CPU Cooler methods
	AddCpuCooler(ctx context.Context, in *CpuCoolerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateCpuCooler(ctx context.Context, in *UpdateCpuCoolerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCpuCooler(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Case methods
	AddCase(ctx context.Context, in *CaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateCase(ctx context.Context, in *UpdateCaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCase(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// PSU methods
	AddPsu(ctx context.Context, in *PsuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdatePsu(ctx context.Context, in *UpdatePsuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeletePsu(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CPU Socket methods
	AddCpuSocket(ctx context.Context, in *CpuSocketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateCpuSocket(ctx context.Context, in *UpdateCpuSocketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCpuSocket(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Motherboard Form Factor methods
	AddMotherboardFormFactor(ctx context.Context, in *MotherboardFormFactorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateMotherboardFormFactor(ctx context.Context, in *UpdateMotherboardFormFactorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteMotherboardFormFactor(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CPU methods
	AddCpu(ctx context.Context, in *CpuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateCpu(ctx context.Context, in *UpdateCpuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCpu(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Motherboard methods
	AddMotherboard(ctx context.Context, in *MotherboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateMotherboard(ctx context.Context, in *UpdateMotherboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteMotherboard(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RAM Kit методы
	AddRAMKit(ctx context.Context, in *RAMKitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateRAMKit(ctx context.Context, in *UpdateRAMKitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteRAMKit(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Storage Drive методы
	AddStorageDrive(ctx context.Context, in *StorageDriveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateStorageDrive(ctx context.Context, in *UpdateStorageDriveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteStorageDrive(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// User методы
	AddUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Shop методы
	AddShop(ctx context.Context, in *ShopRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateShop(ctx context.Context, in *UpdateShopRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteShop(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Product Offer методы
	AddProductOffer(ctx context.Context, in *ProductOfferRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateProductOffer(ctx context.Context, in *UpdateProductOfferRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteProductOffer(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Assembly методы
	AddAssembly(ctx context.Context, in *AssemblyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateAssembly(ctx context.Context, in *UpdateAssemblyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAssembly(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Cooler Socket методы (many-to-many)
	AddCoolerSocket(ctx context.Context, in *CoolerSocketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCoolerSocket(ctx context.Context, in *DeleteCoolerSocketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCoolerSocketsByCooler(ctx context.Context, in *DeleteByCoolerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Case Form Factor Support методы (many-to-many)
	AddCaseFormFactorSupport(ctx context.Context, in *CaseFormFactorSupportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCaseFormFactorSupport(ctx context.Context, in *DeleteCaseFormFactorSupportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCaseFormFactorSupportsByCase(ctx context.Context, in *DeleteByCaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Assembly RAM Kit методы (many-to-many)
	AddAssemblyRAMKit(ctx context.Context, in *AssemblyRAMKitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAssemblyRAMKit(ctx context.Context, in *DeleteAssemblyRAMKitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAssemblyRAMKitsByAssembly(ctx context.Context, in *DeleteByAssemblyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Assembly Drive методы (many-to-many)
	AddAssemblyDrive(ctx context.Context, in *AssemblyDriveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAssemblyDrive(ctx context.Context, in *DeleteAssemblyDriveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAssemblyDrivesByAssembly(ctx context.Context, in *DeleteByAssemblyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type updateClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateClient(cc grpc.ClientConnInterface) UpdateClient {
	return &updateClient{cc}
}

func (c *updateClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddGpu(ctx context.Context, in *GpuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddGpu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateGpu(ctx context.Context, in *UpdateGpuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateGpu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteGpu(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteGpu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddCpuCooler(ctx context.Context, in *CpuCoolerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddCpuCooler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateCpuCooler(ctx context.Context, in *UpdateCpuCoolerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateCpuCooler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteCpuCooler(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteCpuCooler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddCase(ctx context.Context, in *CaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateCase(ctx context.Context, in *UpdateCaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteCase(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddPsu(ctx context.Context, in *PsuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddPsu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdatePsu(ctx context.Context, in *UpdatePsuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdatePsu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeletePsu(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeletePsu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddCpuSocket(ctx context.Context, in *CpuSocketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddCpuSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateCpuSocket(ctx context.Context, in *UpdateCpuSocketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateCpuSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteCpuSocket(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteCpuSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddMotherboardFormFactor(ctx context.Context, in *MotherboardFormFactorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddMotherboardFormFactor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateMotherboardFormFactor(ctx context.Context, in *UpdateMotherboardFormFactorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateMotherboardFormFactor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteMotherboardFormFactor(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteMotherboardFormFactor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddCpu(ctx context.Context, in *CpuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddCpu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateCpu(ctx context.Context, in *UpdateCpuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateCpu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteCpu(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteCpu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddMotherboard(ctx context.Context, in *MotherboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddMotherboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateMotherboard(ctx context.Context, in *UpdateMotherboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateMotherboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteMotherboard(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteMotherboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddRAMKit(ctx context.Context, in *RAMKitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddRAMKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateRAMKit(ctx context.Context, in *UpdateRAMKitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateRAMKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteRAMKit(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteRAMKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddStorageDrive(ctx context.Context, in *StorageDriveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddStorageDrive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateStorageDrive(ctx context.Context, in *UpdateStorageDriveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateStorageDrive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteStorageDrive(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteStorageDrive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddShop(ctx context.Context, in *ShopRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateShop(ctx context.Context, in *UpdateShopRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteShop(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddProductOffer(ctx context.Context, in *ProductOfferRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddProductOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateProductOffer(ctx context.Context, in *UpdateProductOfferRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateProductOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteProductOffer(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteProductOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddAssembly(ctx context.Context, in *AssemblyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddAssembly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) UpdateAssembly(ctx context.Context, in *UpdateAssemblyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_UpdateAssembly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteAssembly(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteAssembly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddCoolerSocket(ctx context.Context, in *CoolerSocketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddCoolerSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteCoolerSocket(ctx context.Context, in *DeleteCoolerSocketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteCoolerSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteCoolerSocketsByCooler(ctx context.Context, in *DeleteByCoolerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteCoolerSocketsByCooler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddCaseFormFactorSupport(ctx context.Context, in *CaseFormFactorSupportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddCaseFormFactorSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteCaseFormFactorSupport(ctx context.Context, in *DeleteCaseFormFactorSupportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteCaseFormFactorSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteCaseFormFactorSupportsByCase(ctx context.Context, in *DeleteByCaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteCaseFormFactorSupportsByCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddAssemblyRAMKit(ctx context.Context, in *AssemblyRAMKitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddAssemblyRAMKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteAssemblyRAMKit(ctx context.Context, in *DeleteAssemblyRAMKitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteAssemblyRAMKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteAssemblyRAMKitsByAssembly(ctx context.Context, in *DeleteByAssemblyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteAssemblyRAMKitsByAssembly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) AddAssemblyDrive(ctx context.Context, in *AssemblyDriveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_AddAssemblyDrive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteAssemblyDrive(ctx context.Context, in *DeleteAssemblyDriveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteAssemblyDrive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) DeleteAssemblyDrivesByAssembly(ctx context.Context, in *DeleteByAssemblyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Update_DeleteAssemblyDrivesByAssembly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateServer is the server API for Update service.
// All implementations must embed UnimplementedUpdateServer
// for forward compatibility.
type UpdateServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// GPU methods
	AddGpu(context.Context, *GpuRequest) (*emptypb.Empty, error)
	UpdateGpu(context.Context, *UpdateGpuRequest) (*emptypb.Empty, error)
	DeleteGpu(context.Context, *IdRequest) (*emptypb.Empty, error)
	// CPU Cooler methods
	AddCpuCooler(context.Context, *CpuCoolerRequest) (*emptypb.Empty, error)
	UpdateCpuCooler(context.Context, *UpdateCpuCoolerRequest) (*emptypb.Empty, error)
	DeleteCpuCooler(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Case methods
	AddCase(context.Context, *CaseRequest) (*emptypb.Empty, error)
	UpdateCase(context.Context, *UpdateCaseRequest) (*emptypb.Empty, error)
	DeleteCase(context.Context, *IdRequest) (*emptypb.Empty, error)
	// PSU methods
	AddPsu(context.Context, *PsuRequest) (*emptypb.Empty, error)
	UpdatePsu(context.Context, *UpdatePsuRequest) (*emptypb.Empty, error)
	DeletePsu(context.Context, *IdRequest) (*emptypb.Empty, error)
	// CPU Socket methods
	AddCpuSocket(context.Context, *CpuSocketRequest) (*emptypb.Empty, error)
	UpdateCpuSocket(context.Context, *UpdateCpuSocketRequest) (*emptypb.Empty, error)
	DeleteCpuSocket(context.Context, *StringRequest) (*emptypb.Empty, error)
	// Motherboard Form Factor methods
	AddMotherboardFormFactor(context.Context, *MotherboardFormFactorRequest) (*emptypb.Empty, error)
	UpdateMotherboardFormFactor(context.Context, *UpdateMotherboardFormFactorRequest) (*emptypb.Empty, error)
	DeleteMotherboardFormFactor(context.Context, *StringRequest) (*emptypb.Empty, error)
	// CPU methods
	AddCpu(context.Context, *CpuRequest) (*emptypb.Empty, error)
	UpdateCpu(context.Context, *UpdateCpuRequest) (*emptypb.Empty, error)
	DeleteCpu(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Motherboard methods
	AddMotherboard(context.Context, *MotherboardRequest) (*emptypb.Empty, error)
	UpdateMotherboard(context.Context, *UpdateMotherboardRequest) (*emptypb.Empty, error)
	DeleteMotherboard(context.Context, *IdRequest) (*emptypb.Empty, error)
	// RAM Kit методы
	AddRAMKit(context.Context, *RAMKitRequest) (*emptypb.Empty, error)
	UpdateRAMKit(context.Context, *UpdateRAMKitRequest) (*emptypb.Empty, error)
	DeleteRAMKit(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Storage Drive методы
	AddStorageDrive(context.Context, *StorageDriveRequest) (*emptypb.Empty, error)
	UpdateStorageDrive(context.Context, *UpdateStorageDriveRequest) (*emptypb.Empty, error)
	DeleteStorageDrive(context.Context, *IdRequest) (*emptypb.Empty, error)
	// User методы
	AddUser(context.Context, *UserRequest) (*emptypb.Empty, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*emptypb.Empty, error)
	DeleteUser(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Shop методы
	AddShop(context.Context, *ShopRequest) (*emptypb.Empty, error)
	UpdateShop(context.Context, *UpdateShopRequest) (*emptypb.Empty, error)
	DeleteShop(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Product Offer методы
	AddProductOffer(context.Context, *ProductOfferRequest) (*emptypb.Empty, error)
	UpdateProductOffer(context.Context, *UpdateProductOfferRequest) (*emptypb.Empty, error)
	DeleteProductOffer(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Assembly методы
	AddAssembly(context.Context, *AssemblyRequest) (*emptypb.Empty, error)
	UpdateAssembly(context.Context, *UpdateAssemblyRequest) (*emptypb.Empty, error)
	DeleteAssembly(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Cooler Socket методы (many-to-many)
	AddCoolerSocket(context.Context, *CoolerSocketRequest) (*emptypb.Empty, error)
	DeleteCoolerSocket(context.Context, *DeleteCoolerSocketRequest) (*emptypb.Empty, error)
	DeleteCoolerSocketsByCooler(context.Context, *DeleteByCoolerRequest) (*emptypb.Empty, error)
	// Case Form Factor Support методы (many-to-many)
	AddCaseFormFactorSupport(context.Context, *CaseFormFactorSupportRequest) (*emptypb.Empty, error)
	DeleteCaseFormFactorSupport(context.Context, *DeleteCaseFormFactorSupportRequest) (*emptypb.Empty, error)
	DeleteCaseFormFactorSupportsByCase(context.Context, *DeleteByCaseRequest) (*emptypb.Empty, error)
	// Assembly RAM Kit методы (many-to-many)
	AddAssemblyRAMKit(context.Context, *AssemblyRAMKitRequest) (*emptypb.Empty, error)
	DeleteAssemblyRAMKit(context.Context, *DeleteAssemblyRAMKitRequest) (*emptypb.Empty, error)
	DeleteAssemblyRAMKitsByAssembly(context.Context, *DeleteByAssemblyRequest) (*emptypb.Empty, error)
	// Assembly Drive методы (many-to-many)
	AddAssemblyDrive(context.Context, *AssemblyDriveRequest) (*emptypb.Empty, error)
	DeleteAssemblyDrive(context.Context, *DeleteAssemblyDriveRequest) (*emptypb.Empty, error)
	DeleteAssemblyDrivesByAssembly(context.Context, *DeleteByAssemblyRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedUpdateServer()
}

// UnimplementedUpdateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateServer struct{}

func (UnimplementedUpdateServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedUpdateServer) AddGpu(context.Context, *GpuRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGpu not implemented")
}
func (UnimplementedUpdateServer) UpdateGpu(context.Context, *UpdateGpuRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGpu not implemented")
}
func (UnimplementedUpdateServer) DeleteGpu(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGpu not implemented")
}
func (UnimplementedUpdateServer) AddCpuCooler(context.Context, *CpuCoolerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCpuCooler not implemented")
}
func (UnimplementedUpdateServer) UpdateCpuCooler(context.Context, *UpdateCpuCoolerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCpuCooler not implemented")
}
func (UnimplementedUpdateServer) DeleteCpuCooler(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCpuCooler not implemented")
}
func (UnimplementedUpdateServer) AddCase(context.Context, *CaseRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCase not implemented")
}
func (UnimplementedUpdateServer) UpdateCase(context.Context, *UpdateCaseRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCase not implemented")
}
func (UnimplementedUpdateServer) DeleteCase(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCase not implemented")
}
func (UnimplementedUpdateServer) AddPsu(context.Context, *PsuRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPsu not implemented")
}
func (UnimplementedUpdateServer) UpdatePsu(context.Context, *UpdatePsuRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePsu not implemented")
}
func (UnimplementedUpdateServer) DeletePsu(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePsu not implemented")
}
func (UnimplementedUpdateServer) AddCpuSocket(context.Context, *CpuSocketRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCpuSocket not implemented")
}
func (UnimplementedUpdateServer) UpdateCpuSocket(context.Context, *UpdateCpuSocketRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCpuSocket not implemented")
}
func (UnimplementedUpdateServer) DeleteCpuSocket(context.Context, *StringRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCpuSocket not implemented")
}
func (UnimplementedUpdateServer) AddMotherboardFormFactor(context.Context, *MotherboardFormFactorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMotherboardFormFactor not implemented")
}
func (UnimplementedUpdateServer) UpdateMotherboardFormFactor(context.Context, *UpdateMotherboardFormFactorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMotherboardFormFactor not implemented")
}
func (UnimplementedUpdateServer) DeleteMotherboardFormFactor(context.Context, *StringRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMotherboardFormFactor not implemented")
}
func (UnimplementedUpdateServer) AddCpu(context.Context, *CpuRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCpu not implemented")
}
func (UnimplementedUpdateServer) UpdateCpu(context.Context, *UpdateCpuRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCpu not implemented")
}
func (UnimplementedUpdateServer) DeleteCpu(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCpu not implemented")
}
func (UnimplementedUpdateServer) AddMotherboard(context.Context, *MotherboardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMotherboard not implemented")
}
func (UnimplementedUpdateServer) UpdateMotherboard(context.Context, *UpdateMotherboardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMotherboard not implemented")
}
func (UnimplementedUpdateServer) DeleteMotherboard(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMotherboard not implemented")
}
func (UnimplementedUpdateServer) AddRAMKit(context.Context, *RAMKitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRAMKit not implemented")
}
func (UnimplementedUpdateServer) UpdateRAMKit(context.Context, *UpdateRAMKitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRAMKit not implemented")
}
func (UnimplementedUpdateServer) DeleteRAMKit(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRAMKit not implemented")
}
func (UnimplementedUpdateServer) AddStorageDrive(context.Context, *StorageDriveRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStorageDrive not implemented")
}
func (UnimplementedUpdateServer) UpdateStorageDrive(context.Context, *UpdateStorageDriveRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStorageDrive not implemented")
}
func (UnimplementedUpdateServer) DeleteStorageDrive(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStorageDrive not implemented")
}
func (UnimplementedUpdateServer) AddUser(context.Context, *UserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedUpdateServer) UpdateUser(context.Context, *UpdateUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUpdateServer) DeleteUser(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUpdateServer) AddShop(context.Context, *ShopRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddShop not implemented")
}
func (UnimplementedUpdateServer) UpdateShop(context.Context, *UpdateShopRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShop not implemented")
}
func (UnimplementedUpdateServer) DeleteShop(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShop not implemented")
}
func (UnimplementedUpdateServer) AddProductOffer(context.Context, *ProductOfferRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProductOffer not implemented")
}
func (UnimplementedUpdateServer) UpdateProductOffer(context.Context, *UpdateProductOfferRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductOffer not implemented")
}
func (UnimplementedUpdateServer) DeleteProductOffer(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductOffer not implemented")
}
func (UnimplementedUpdateServer) AddAssembly(context.Context, *AssemblyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAssembly not implemented")
}
func (UnimplementedUpdateServer) UpdateAssembly(context.Context, *UpdateAssemblyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssembly not implemented")
}
func (UnimplementedUpdateServer) DeleteAssembly(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssembly not implemented")
}
func (UnimplementedUpdateServer) AddCoolerSocket(context.Context, *CoolerSocketRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCoolerSocket not implemented")
}
func (UnimplementedUpdateServer) DeleteCoolerSocket(context.Context, *DeleteCoolerSocketRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCoolerSocket not implemented")
}
func (UnimplementedUpdateServer) DeleteCoolerSocketsByCooler(context.Context, *DeleteByCoolerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCoolerSocketsByCooler not implemented")
}
func (UnimplementedUpdateServer) AddCaseFormFactorSupport(context.Context, *CaseFormFactorSupportRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCaseFormFactorSupport not implemented")
}
func (UnimplementedUpdateServer) DeleteCaseFormFactorSupport(context.Context, *DeleteCaseFormFactorSupportRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCaseFormFactorSupport not implemented")
}
func (UnimplementedUpdateServer) DeleteCaseFormFactorSupportsByCase(context.Context, *DeleteByCaseRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCaseFormFactorSupportsByCase not implemented")
}
func (UnimplementedUpdateServer) AddAssemblyRAMKit(context.Context, *AssemblyRAMKitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAssemblyRAMKit not implemented")
}
func (UnimplementedUpdateServer) DeleteAssemblyRAMKit(context.Context, *DeleteAssemblyRAMKitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssemblyRAMKit not implemented")
}
func (UnimplementedUpdateServer) DeleteAssemblyRAMKitsByAssembly(context.Context, *DeleteByAssemblyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssemblyRAMKitsByAssembly not implemented")
}
func (UnimplementedUpdateServer) AddAssemblyDrive(context.Context, *AssemblyDriveRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAssemblyDrive not implemented")
}
func (UnimplementedUpdateServer) DeleteAssemblyDrive(context.Context, *DeleteAssemblyDriveRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssemblyDrive not implemented")
}
func (UnimplementedUpdateServer) DeleteAssemblyDrivesByAssembly(context.Context, *DeleteByAssemblyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssemblyDrivesByAssembly not implemented")
}
func (UnimplementedUpdateServer) mustEmbedUnimplementedUpdateServer() {}
func (UnimplementedUpdateServer) testEmbeddedByValue()                {}

// UnsafeUpdateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateServer will
// result in compilation errors.
type UnsafeUpdateServer interface {
	mustEmbedUnimplementedUpdateServer()
}

func RegisterUpdateServer(s grpc.ServiceRegistrar, srv UpdateServer) {
	// If the following call pancis, it indicates UnimplementedUpdateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Update_ServiceDesc, srv)
}

func _Update_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddGpu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GpuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddGpu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddGpu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddGpu(ctx, req.(*GpuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateGpu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGpuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateGpu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateGpu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateGpu(ctx, req.(*UpdateGpuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteGpu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteGpu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteGpu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteGpu(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddCpuCooler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CpuCoolerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddCpuCooler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddCpuCooler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddCpuCooler(ctx, req.(*CpuCoolerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateCpuCooler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCpuCoolerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateCpuCooler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateCpuCooler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateCpuCooler(ctx, req.(*UpdateCpuCoolerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteCpuCooler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteCpuCooler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteCpuCooler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteCpuCooler(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddCase(ctx, req.(*CaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateCase(ctx, req.(*UpdateCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteCase(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddPsu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PsuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddPsu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddPsu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddPsu(ctx, req.(*PsuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdatePsu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePsuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdatePsu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdatePsu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdatePsu(ctx, req.(*UpdatePsuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeletePsu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeletePsu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeletePsu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeletePsu(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddCpuSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CpuSocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddCpuSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddCpuSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddCpuSocket(ctx, req.(*CpuSocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateCpuSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCpuSocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateCpuSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateCpuSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateCpuSocket(ctx, req.(*UpdateCpuSocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteCpuSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteCpuSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteCpuSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteCpuSocket(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddMotherboardFormFactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MotherboardFormFactorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddMotherboardFormFactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddMotherboardFormFactor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddMotherboardFormFactor(ctx, req.(*MotherboardFormFactorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateMotherboardFormFactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMotherboardFormFactorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateMotherboardFormFactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateMotherboardFormFactor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateMotherboardFormFactor(ctx, req.(*UpdateMotherboardFormFactorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteMotherboardFormFactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteMotherboardFormFactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteMotherboardFormFactor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteMotherboardFormFactor(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddCpu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CpuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddCpu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddCpu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddCpu(ctx, req.(*CpuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateCpu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCpuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateCpu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateCpu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateCpu(ctx, req.(*UpdateCpuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteCpu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteCpu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteCpu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteCpu(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddMotherboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MotherboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddMotherboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddMotherboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddMotherboard(ctx, req.(*MotherboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateMotherboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMotherboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateMotherboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateMotherboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateMotherboard(ctx, req.(*UpdateMotherboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteMotherboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteMotherboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteMotherboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteMotherboard(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddRAMKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAMKitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddRAMKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddRAMKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddRAMKit(ctx, req.(*RAMKitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateRAMKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRAMKitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateRAMKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateRAMKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateRAMKit(ctx, req.(*UpdateRAMKitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteRAMKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteRAMKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteRAMKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteRAMKit(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddStorageDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddStorageDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddStorageDrive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddStorageDrive(ctx, req.(*StorageDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateStorageDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStorageDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateStorageDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateStorageDrive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateStorageDrive(ctx, req.(*UpdateStorageDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteStorageDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteStorageDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteStorageDrive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteStorageDrive(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteUser(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddShop(ctx, req.(*ShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateShop(ctx, req.(*UpdateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteShop(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddProductOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddProductOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddProductOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddProductOffer(ctx, req.(*ProductOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateProductOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateProductOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateProductOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateProductOffer(ctx, req.(*UpdateProductOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteProductOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteProductOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteProductOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteProductOffer(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddAssembly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssemblyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddAssembly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddAssembly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddAssembly(ctx, req.(*AssemblyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_UpdateAssembly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssemblyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).UpdateAssembly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_UpdateAssembly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).UpdateAssembly(ctx, req.(*UpdateAssemblyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteAssembly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteAssembly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteAssembly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteAssembly(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddCoolerSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoolerSocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddCoolerSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddCoolerSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddCoolerSocket(ctx, req.(*CoolerSocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteCoolerSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCoolerSocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteCoolerSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteCoolerSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteCoolerSocket(ctx, req.(*DeleteCoolerSocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteCoolerSocketsByCooler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByCoolerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteCoolerSocketsByCooler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteCoolerSocketsByCooler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteCoolerSocketsByCooler(ctx, req.(*DeleteByCoolerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddCaseFormFactorSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaseFormFactorSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddCaseFormFactorSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddCaseFormFactorSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddCaseFormFactorSupport(ctx, req.(*CaseFormFactorSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteCaseFormFactorSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCaseFormFactorSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteCaseFormFactorSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteCaseFormFactorSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteCaseFormFactorSupport(ctx, req.(*DeleteCaseFormFactorSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteCaseFormFactorSupportsByCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteCaseFormFactorSupportsByCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteCaseFormFactorSupportsByCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteCaseFormFactorSupportsByCase(ctx, req.(*DeleteByCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddAssemblyRAMKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssemblyRAMKitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddAssemblyRAMKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddAssemblyRAMKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddAssemblyRAMKit(ctx, req.(*AssemblyRAMKitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteAssemblyRAMKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssemblyRAMKitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteAssemblyRAMKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteAssemblyRAMKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteAssemblyRAMKit(ctx, req.(*DeleteAssemblyRAMKitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteAssemblyRAMKitsByAssembly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByAssemblyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteAssemblyRAMKitsByAssembly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteAssemblyRAMKitsByAssembly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteAssemblyRAMKitsByAssembly(ctx, req.(*DeleteByAssemblyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_AddAssemblyDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssemblyDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).AddAssemblyDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_AddAssemblyDrive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).AddAssemblyDrive(ctx, req.(*AssemblyDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteAssemblyDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssemblyDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteAssemblyDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteAssemblyDrive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteAssemblyDrive(ctx, req.(*DeleteAssemblyDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_DeleteAssemblyDrivesByAssembly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByAssemblyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).DeleteAssemblyDrivesByAssembly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_DeleteAssemblyDrivesByAssembly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).DeleteAssemblyDrivesByAssembly(ctx, req.(*DeleteByAssemblyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Update_ServiceDesc is the grpc.ServiceDesc for Update service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Update_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "update.Update",
	HandlerType: (*UpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Update_Ping_Handler,
		},
		{
			MethodName: "AddGpu",
			Handler:    _Update_AddGpu_Handler,
		},
		{
			MethodName: "UpdateGpu",
			Handler:    _Update_UpdateGpu_Handler,
		},
		{
			MethodName: "DeleteGpu",
			Handler:    _Update_DeleteGpu_Handler,
		},
		{
			MethodName: "AddCpuCooler",
			Handler:    _Update_AddCpuCooler_Handler,
		},
		{
			MethodName: "UpdateCpuCooler",
			Handler:    _Update_UpdateCpuCooler_Handler,
		},
		{
			MethodName: "DeleteCpuCooler",
			Handler:    _Update_DeleteCpuCooler_Handler,
		},
		{
			MethodName: "AddCase",
			Handler:    _Update_AddCase_Handler,
		},
		{
			MethodName: "UpdateCase",
			Handler:    _Update_UpdateCase_Handler,
		},
		{
			MethodName: "DeleteCase",
			Handler:    _Update_DeleteCase_Handler,
		},
		{
			MethodName: "AddPsu",
			Handler:    _Update_AddPsu_Handler,
		},
		{
			MethodName: "UpdatePsu",
			Handler:    _Update_UpdatePsu_Handler,
		},
		{
			MethodName: "DeletePsu",
			Handler:    _Update_DeletePsu_Handler,
		},
		{
			MethodName: "AddCpuSocket",
			Handler:    _Update_AddCpuSocket_Handler,
		},
		{
			MethodName: "UpdateCpuSocket",
			Handler:    _Update_UpdateCpuSocket_Handler,
		},
		{
			MethodName: "DeleteCpuSocket",
			Handler:    _Update_DeleteCpuSocket_Handler,
		},
		{
			MethodName: "AddMotherboardFormFactor",
			Handler:    _Update_AddMotherboardFormFactor_Handler,
		},
		{
			MethodName: "UpdateMotherboardFormFactor",
			Handler:    _Update_UpdateMotherboardFormFactor_Handler,
		},
		{
			MethodName: "DeleteMotherboardFormFactor",
			Handler:    _Update_DeleteMotherboardFormFactor_Handler,
		},
		{
			MethodName: "AddCpu",
			Handler:    _Update_AddCpu_Handler,
		},
		{
			MethodName: "UpdateCpu",
			Handler:    _Update_UpdateCpu_Handler,
		},
		{
			MethodName: "DeleteCpu",
			Handler:    _Update_DeleteCpu_Handler,
		},
		{
			MethodName: "AddMotherboard",
			Handler:    _Update_AddMotherboard_Handler,
		},
		{
			MethodName: "UpdateMotherboard",
			Handler:    _Update_UpdateMotherboard_Handler,
		},
		{
			MethodName: "DeleteMotherboard",
			Handler:    _Update_DeleteMotherboard_Handler,
		},
		{
			MethodName: "AddRAMKit",
			Handler:    _Update_AddRAMKit_Handler,
		},
		{
			MethodName: "UpdateRAMKit",
			Handler:    _Update_UpdateRAMKit_Handler,
		},
		{
			MethodName: "DeleteRAMKit",
			Handler:    _Update_DeleteRAMKit_Handler,
		},
		{
			MethodName: "AddStorageDrive",
			Handler:    _Update_AddStorageDrive_Handler,
		},
		{
			MethodName: "UpdateStorageDrive",
			Handler:    _Update_UpdateStorageDrive_Handler,
		},
		{
			MethodName: "DeleteStorageDrive",
			Handler:    _Update_DeleteStorageDrive_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _Update_AddUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Update_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Update_DeleteUser_Handler,
		},
		{
			MethodName: "AddShop",
			Handler:    _Update_AddShop_Handler,
		},
		{
			MethodName: "UpdateShop",
			Handler:    _Update_UpdateShop_Handler,
		},
		{
			MethodName: "DeleteShop",
			Handler:    _Update_DeleteShop_Handler,
		},
		{
			MethodName: "AddProductOffer",
			Handler:    _Update_AddProductOffer_Handler,
		},
		{
			MethodName: "UpdateProductOffer",
			Handler:    _Update_UpdateProductOffer_Handler,
		},
		{
			MethodName: "DeleteProductOffer",
			Handler:    _Update_DeleteProductOffer_Handler,
		},
		{
			MethodName: "AddAssembly",
			Handler:    _Update_AddAssembly_Handler,
		},
		{
			MethodName: "UpdateAssembly",
			Handler:    _Update_UpdateAssembly_Handler,
		},
		{
			MethodName: "DeleteAssembly",
			Handler:    _Update_DeleteAssembly_Handler,
		},
		{
			MethodName: "AddCoolerSocket",
			Handler:    _Update_AddCoolerSocket_Handler,
		},
		{
			MethodName: "DeleteCoolerSocket",
			Handler:    _Update_DeleteCoolerSocket_Handler,
		},
		{
			MethodName: "DeleteCoolerSocketsByCooler",
			Handler:    _Update_DeleteCoolerSocketsByCooler_Handler,
		},
		{
			MethodName: "AddCaseFormFactorSupport",
			Handler:    _Update_AddCaseFormFactorSupport_Handler,
		},
		{
			MethodName: "DeleteCaseFormFactorSupport",
			Handler:    _Update_DeleteCaseFormFactorSupport_Handler,
		},
		{
			MethodName: "DeleteCaseFormFactorSupportsByCase",
			Handler:    _Update_DeleteCaseFormFactorSupportsByCase_Handler,
		},
		{
			MethodName: "AddAssemblyRAMKit",
			Handler:    _Update_AddAssemblyRAMKit_Handler,
		},
		{
			MethodName: "DeleteAssemblyRAMKit",
			Handler:    _Update_DeleteAssemblyRAMKit_Handler,
		},
		{
			MethodName: "DeleteAssemblyRAMKitsByAssembly",
			Handler:    _Update_DeleteAssemblyRAMKitsByAssembly_Handler,
		},
		{
			MethodName: "AddAssemblyDrive",
			Handler:    _Update_AddAssemblyDrive_Handler,
		},
		{
			MethodName: "DeleteAssemblyDrive",
			Handler:    _Update_DeleteAssemblyDrive_Handler,
		},
		{
			MethodName: "DeleteAssemblyDrivesByAssembly",
			Handler:    _Update_DeleteAssemblyDrivesByAssembly_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "update.proto",
}
